include: package:flutter_lints/flutter.yaml

# Define la longitud de línea para el formateador 'dart format'.
# Esta es una clave de primer nivel, no va dentro de 'analyzer' ni 'formatter'.
line_length: 80

analyzer:
  # Excluye los archivos generados automáticamente (como los de localización)
  # para que el analizador no se queje de ellos.
  exclude:
    - "lib/src/core/l10n/**"

# Aquí definimos nuestras reglas personalizadas (el Linter).
linter:
  rules:
    # --- REGLAS DE ESTILO (Consistencia) ---
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_relative_imports: true
    sort_child_properties_last: true
    unnecessary_this: true
    always_specify_types: false
    
    # --- REGLAS DE LIMPIEZA (Código muerto) ---
    avoid_print: true
    avoid_redundant_argument_values: true
    
    # --- REGLAS DE FORMATO ---
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true